<?php echo"
<nav>
    <ul>
    <li><img src='images/logo.png' alt='HAZ Web Design Logo'></li>
    <li><a href='index.php'>Home</a></li>
    <li><a href= 'about.php'>About Us</a></li>
    <li><a href='jobs.php'> Openings</a></li>
    <li><a href='apply.php'> Apply Now</a></li>
    <li><a href='manage.php'> Managers</a></li>
    <li><a href='mailto:info@hazwebdesign.com.au'>Email Us</a></li>
    </ul>
</nav>";
?>